on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    # services:
    #   mysql:
    #     image: mysql:8
    #     env:
    #       MYSQL_ROOT_PASSWORD: test
    #       MYSQL_DATABASE: test
    #     ports:
    #       - 3306:3306
    #     options: >-
    #       --health-cmd="mysqladmin ping --silent"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3

    # env:
    #   DB_HOST: 127.0.0.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Wait for MySQL to be ready
    #   run: |
    #     until mysqladmin ping -h"${{ env.DB_HOST }}" --silent; do
    #       echo 'waiting for mysql...'
    #       sleep 5
    #     done

    - name: Run tests
      run: npm test

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push Docker image
    #   run: |
    #     docker build -t cybersepo/sepocms:latest .
    #     docker push cybersepo/sepocms:latest
